# egress from app-pod to db-pod
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-to-db-pod
  namespace: development
spec:
  podSelector:
    matchLabels:
      pod: app-pod
  policyTypes:
    - Egress
  egress:
    - to:
      - podSelector:
          matchLabels:
            pod: db-pod
      - namespaceSelector:
          matchLabels:
            env: prod
            

--- 

# ingress on db-pod allowing traffic from app-pod

# egress from app-pod to db-pod
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-from-app-pod
  namespace: development
spec:
  podSelector:
    matchLabels:
      pod: db-pod
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            pod: app-pod